apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel-target
resources:
  - namespace.yaml
  - otel-collector-config.yaml
  - otel-collector.yaml
  - postgres.yaml
  - redis.yaml
  - gateway.yaml
  - orders.yaml
  - payments.yaml
  - inventory.yaml
  - worker.yaml
  - networkpolicy.yaml

