apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: sentinel-target
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch: {}
    exporters:
      logging:
        verbosity: detailed
      debug:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, debug]

