apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: sentinel-target
type: Opaque
stringData:
  POSTGRES_USER: sentinel
  POSTGRES_PASSWORD: sentinel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: sentinel-target
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: postgres-credentials
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          emptyDir: {}
        - name: init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: sentinel-target
data:
  001-create-dbs.sql: |
    CREATE DATABASE orders_db;
    CREATE DATABASE payments_db;
    CREATE DATABASE inventory_db;
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sentinel-target
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

